### ISSUE TITLE
invalid option: --format 

### ISSUE THREAD

**Issue by fatsolko** [CycloneDX/cyclonedx-ruby-gem#31]
```
$ cyclonedx-ruby --path . --format json
/bundle/gems/cyclonedx-ruby-1.1.0/lib/bom_builder.rb:68:in `setup': invalid option: --format (OptionParser::InvalidOption)
	from /bundle/gems/cyclonedx-ruby-1.1.0/lib/bom_builder.rb:15:in `build'
	from /bundle/gems/cyclonedx-ruby-1.1.0/bin/cyclonedx-ruby:4:in `<top (required)>'
	from /bundle/bin/cyclonedx-ruby:23:in `load'
	from /bundle/bin/cyclonedx-ruby:23:in `<main>'
```
format is in readme.md, but didn't work

**Comment by fatsolko** [comment]
I think need to add 1.2.0 version into ruby gem hub

**Comment by kernelsmith** [comment]
Yeah, 1.1 is the latest on rubygems.org

**Comment by jamis** [comment]
I see that @ryancammer bumped the version on GitHub to 1.2.0 with fd1c2b63f319535081238288344983d76599f50c, almost a full year ago. Is there anything holding back a proper gem release? /cc @stevespringett, et. al.

**Comment by pboling** [comment]
This will be fixed in the next release. We are working on it!

@jamis The holdup on release is someone putting in the time to setup the secure publishing GH => RG.O.
